services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.8
    container_name: clickhouse
    ports:
      - "8123:8123"  # HTTP интерфейс
      - "9003:9000"  # TCP интерфейс
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: logs
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""

  grafana:
    image: grafana/grafana:9.3.6
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"  # панель управления
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

# docker-compose logs minio-init
  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      sh -c "
      until mc alias set myminio http://minio:9000 minioadmin minioadmin; do echo 'Waiting for MinIO...'; sleep 2; done;
      mc mb myminio/bucket-spark || echo 'Bucket already exists';
      mc cp --recursive /model/* myminio/bucket-spark/model/ || echo 'File copy failed';
      "
    volumes:
      - "/c/Users/admin/Desktop/Diplom/LogAnalysisMicroservice/SparkMLModel/model:/model" # локальная папка с моделью
    restart: "no"

volumes:
  minio-data:
  clickhouse_data:
